---

# install required packaages

- include: ../../../portage/tasks/gentoo/main.yml
  vars:
    portage_configuration:
      - section: "package.use"
        file: "openproject"
        entries:
          - "dev-libs/openssl -bindist"
          - "net-misc/openssh -bindist"
      - section: "package.use"
        file: "git"
        entries:
          - "dev-vcs/git -perl -gpg -webdav"
      - section: "package.accept_keywords"
        file: "openproject"
        entries:
          - ">=www-apache/passenger-5.0.30 ~amd64"
    portage_packages:
      # openssl and openssh need to be reinstalled without bindist used when compiling ruby
      - { package: "net-misc/openssh" }
      - { package: "media-gfx/imagemagick" }
      # git need to be reinstalled with curl use flag
      - { package: "dev-vcs/git" }
      - { package: "net-misc/curl" }
      - { package: "net-misc/memcached" }
      - { package: "dev-lang/ruby" }
      - { package: "net-libs/nodejs" }
      - { package: "www-apache/passenger" }


# secure up memcache configuration

- name: write memcache configuration
  become: yes
  lineinfile: dest="/etc/conf.d/memcached" regexp="^{{ item.search }}" line="{{ item.replace }}" state="{{ item.state | default('present') }}"
  with_items:
    - { search: "LISTENON=", replace: "LISTENON=\"{{ openproject_memcache_config.listenon }}\"" }
    - { search: "PORT=",     replace: "PORT=\"{{ openproject_memcache_config.port }}\"" }


# ensure services are running

- name: ensure memcache service is running
  become: yes
  service: name="memcached" state="restarted" enabled=yes
