---

- name: mark ruby24 as stable
  become: yes
  lineinfile:
    dest: "/etc/portage/profile/use.stable.mask"
    line: "-ruby_targets_ruby24"
    state: "present"
    create: yes

- import_tasks: ../../../vundb-portage/tasks/gentoo/main.yml
  vars:
    portage_configuration:
      - section: "package.accept_keywords"
        file: "ruby"
        entries:
          - ">=dev-ruby/xmlrpc-0.3.0 ~amd64"
          - ">=dev-ruby/kpeg-1.1.0 ~amd64"
          - ">=dev-ruby/rdoc-6.0.0 ~amd64"
          - ">=dev-ruby/net-telnet-0.1.1-r1 ~amd64"
          - ">=dev-lang/ruby-2.4.2 ~amd64"
          - ">=dev-ruby/minitest-5.10.3 ~amd64"
          - ">=dev-ruby/power_assert-1.1.1 ~amd64"
          - ">=virtual/rubygems-13 ~amd64"
          - ">=dev-ruby/test-unit-3.2.6 ~amd64"
          - ">=dev-ruby/json-2.1.0 ~amd64"#
          - ">=dev-ruby/did_you_mean-1.1.2 ~amd64"
          - ">=dev-ruby/racc-1.4.14 ~amd64"
          - ">=dev-ruby/rake-12.3.0 ~amd64"
      - section: "package.use"
        file: "ruby"
        entries:
          - ">=dev-ruby/xmlrpc-0.3.0 ruby_targets_ruby24"
          - ">=dev-ruby/kpeg-1.1.0 ruby_targets_ruby24"
          - ">=dev-ruby/rdoc-6.0.0 ruby_targets_ruby24"
          - ">=dev-ruby/net-telnet-0.1.1-r1 ruby_targets_ruby24"
          - ">=virtual/rubygems-13 ruby_targets_ruby24"
          - ">=dev-ruby/minitest-5.10.3 ruby_targets_ruby24"
          - ">=dev-ruby/power_assert-1.1.1 ruby_targets_ruby24"
          - ">=dev-ruby/test-unit-3.2.6 ruby_targets_ruby24"
          - ">=dev-ruby/json-2.1.0 ruby_targets_ruby24"
          - ">=dev-ruby/did_you_mean-1.1.2 ruby_targets_ruby24"
          - ">=dev-ruby/racc-1.4.14 ruby_targets_ruby24"
          - ">=dev-ruby/rake-12.3.0 ruby_targets_ruby24"
          - ">=dev-ruby/rubygems-2.6.14 ruby_targets_ruby24"
    portage_packages:
      - { package: ">=dev-lang/ruby-2.4" }

- name: check ruby eselect target
  shell: "eselect ruby list | grep ruby24 | awk -F '[][]' '{print $2}'"
  register: eselect_ruby

- name: set ruby eselect target
  become: yes
  shell: "eselect ruby set {{ eselect_ruby.stdout }}"
